version: '3.9'
services:
  #--MYSQL--#
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-test}
      MYSQL_USER: ${MYSQL_USERNAME:-mysql}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mysql}
    ports:
      - "3306:3306"
    networks:
      - mysql
    volumes:
      - $PWD/mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  #--PHPMYADMIN--#
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      MYSQL_USERNAME: ${MYSQL_USERNAME:-mysql}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    networks:
      - mysql

networks:
  mysql:
    name: mysql
    driver: bridge
volumes:
  #--MYSQL--#
  mysql-data:
    driver: "local"
